name: CI on Branch and pull requests

on:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:
  linting:
    name: Linting
    uses: ./.github/workflows/linting-and-formating.yml
    secrets: inherit

