name: CI on main

on:
  push:
    branches:
      - 'main'

jobs:
  linting:
    name: Linting
    uses: ./.github/workflows/linting-and-formating.yml
  deploy:
    name: Deploy
    uses: ./.github/workflows/deploy-gh-pages.yml

