name: Deploy Github Pages

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          deploy_key: ${{ secrets.WEB_DEPLOY_KEY }}
          cname: jiangxue-xu.com
          external_repository: Studio-TJ/jiangxue-web
          publish_dir: .
          user_name: Studio-TJ-Github-Action[bot]
          user_email:  info@studiotj.cc
