name: Linting and Formatting

on:
  push:

  pull_request:

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lintting with SuperLint
        uses: super-linter/super-linter@v7.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
          FILTER_REGEX_INCLUDE: "^.*/.(html|css)$"

