name: Linting and Formatting

on:
  workflow_call:
    inputs:
      current_branch:
        description: 'The current branch'
        type: string
        required: true
        default: 'main'


jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lintting with SuperLint
        uses: super-linter/super-linter@v7.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
          DEFAULT_BRANCH: ${{ inputs.current_branch }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_HTML: true
          VALIDATE_CSS: true

